# fly.toml app configuration file generated for backend-worlddex on 2025-04-17T13:34:05-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-worlddex'
primary_region = 'ord'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[processes]
  app    = "node dist/index.js"
  worker = "node dist/workers/tier2Worker.js"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
