-- Generated SQL to insert usernames into username_pool table
-- Total usernames: 40

INSERT INTO username_pool (username) VALUES
  ('pickle'),
  ('whiz'),
  ('goop'),
  ('muffin'),
  ('spud'),
  ('zipper'),
  ('noodle'),
  ('fudge'),
  ('blip'),
  ('sneak'),
  ('gizmo'),
  ('puddle'),
  ('crumb'),
  ('waffle'),
  ('doodle'),
  ('skimp'),
  ('glint'),
  ('pebble'),
  ('scoot'),
  ('bloop'),
  ('tweak'),
  ('fluff'),
  ('spark'),
  ('munch'),
  ('twig'),
  ('plop'),
  ('snack'),
  ('rubble'),
  ('gleam'),
  ('tickle'),
  ('bump'),
  ('whirl'),
  ('splat'),
  ('gloop'),
  ('chomp'),
  ('flick'),
  ('smudge'),
  ('trinket'),
  ('boop'),
  ('squawk')
ON CONFLICT (username) DO NOTHING;

